# Generated by Django 5.0.3 on 2024-04-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='', upload_to='projects/images/'),
            preserve_default=False,
        ),
    ]
