# Generated by Django 5.0.3 on 2024-03-30 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialitem',
            name='social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='socials_app.social'),
        ),
    ]
