# Generated by Django 5.0.3 on 2024-03-30 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceplan',
            old_name='paln',
            new_name='plan',
        ),
    ]
