# Generated by Django 5.0.3 on 2024-03-30 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0002_rename_paln_serviceplan_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoption',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_options', to='services_app.service'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_plans', to='services_app.service'),
        ),
    ]
